//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DKHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DKHACHHANG()
        {
            this.TDONHANGs = new HashSet<TDONHANG>();
            this.TDONHANGs1 = new HashSet<TDONHANG>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string FACEBOOKID { get; set; }
        public string GOOGLEID { get; set; }
        public string AVATAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANG> TDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANG> TDONHANGs1 { get; set; }
    }
}
