//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMATHANG()
        {
            this.DANHSANPHAMs = new HashSet<DANHSANPHAM>();
            this.TDONHANGCHITIETs = new HashSet<TDONHANGCHITIET>();
        }
    
        public string ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public string DNHOMMATHANGID { get; set; }
        public string DTHUONGHIEUID { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> COIMEI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSANPHAM> DANHSANPHAMs { get; set; }
        public virtual DNHOMMATHANG DNHOMMATHANG { get; set; }
        public virtual DTHUONGHIEU DTHUONGHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANGCHITIET> TDONHANGCHITIETs { get; set; }
    }
}
