//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTINTUC
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> TIMECREATED { get; set; }
        public string TITLE { get; set; }
        public string NOIDUNG { get; set; }
    }
}
