//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOANEntities : DbContext
    {
        public DOANEntities()
            : base("name=DOANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DANHSANPHAM> DANHSANPHAMs { get; set; }
        public virtual DbSet<DKHACHHANG> DKHACHHANGs { get; set; }
        public virtual DbSet<DKHUYENMAI> DKHUYENMAIs { get; set; }
        public virtual DbSet<DKHUYENMAICHITIET> DKHUYENMAICHITIETs { get; set; }
        public virtual DbSet<DMATHANG> DMATHANGs { get; set; }
        public virtual DbSet<DNHACUNGCAP> DNHACUNGCAPs { get; set; }
        public virtual DbSet<DNHOMMATHANG> DNHOMMATHANGs { get; set; }
        public virtual DbSet<TDONHANG> TDONHANGs { get; set; }
        public virtual DbSet<TDONHANGCHITIET> TDONHANGCHITIETs { get; set; }
    }
}
