//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDONHANG()
        {
            this.TDONHANGCHITIETs = new HashSet<TDONHANGCHITIET>();
            this.TDONHANGCHITIETs1 = new HashSet<TDONHANGCHITIET>();
        }
    
        public string ID { get; set; }
        public Nullable<int> LOAI { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string DKHACHHANGID { get; set; }
        public string DNHACUNGCAPID { get; set; }
        public string DKHUYENMAIID { get; set; }
        public Nullable<decimal> TIENHANG { get; set; }
        public Nullable<decimal> TILEGIAMGIA { get; set; }
        public Nullable<decimal> TIENGIAMGIA { get; set; }
        public Nullable<decimal> TONGCONG { get; set; }
        public Nullable<decimal> TIENTHANHTOAN { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
        public string TENNGUOINHAN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
    
        public virtual DKHACHHANG DKHACHHANG { get; set; }
        public virtual DKHACHHANG DKHACHHANG1 { get; set; }
        public virtual DKHUYENMAI DKHUYENMAI { get; set; }
        public virtual DKHUYENMAI DKHUYENMAI1 { get; set; }
        public virtual DNHACUNGCAP DNHACUNGCAP { get; set; }
        public virtual DNHACUNGCAP DNHACUNGCAP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANGCHITIET> TDONHANGCHITIETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANGCHITIET> TDONHANGCHITIETs1 { get; set; }
    }
}
