//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTHUCHI
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DNHACUNGCAPID { get; set; }
        public Nullable<int> LOAI { get; set; }
        public Nullable<int> THU { get; set; }
        public Nullable<int> CHI { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual DNHACUNGCAP DNHACUNGCAP { get; set; }
    }
}
